CREATE DATABASE clinica;
USE clinica;
CREATE TABLE medico(
	crm VARCHAR(11) NOT NULL PRIMARY KEY,
	nome VARCHAR(100) NOT null
);

CREATE TABLE paciente(
	codigo INT AUTO_INCREMENT,
	cpf VARCHAR(11) NOT NULL UNIQUE,
	nome VARCHAR(100) NOT NULL,
	rg VARCHAR(11) NOT NULL
);

CREATE TABLE atende(
	
);